# AndroidX 统一开关
android.useAndroidX=true
# Kotlin 代码风格官方推荐
kotlin.code.style=official
# 非 Android 模块（纯 JVM）默认改为非传递型 POM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# AndroidX 使用 R8 时不做资源压缩（体量小，无需开启）
android.nonTransitiveRClass=true
# AGP 8.5 + compileSdk 35 的兼容性提示抑制（实际兼容，仅告警）
android.suppressUnsupportedCompileSdk=35
